# Generated by Django 6.0.1 on 2026-01-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('P', 'PREMIUM'), ('N', 'NORMAL')], max_length=10),
        ),
    ]
